services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    image: alesque29/cgd-frontend:latest
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    volumes:
      - static_files:/usr/share/nginx/html
    networks:
      - app-network

  backend:
    image: alesque29/cgd-backend:latest
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    networks:
      - app-network
    expose:
      - "8000"

networks:
  app-network:
    driver: bridge

volumes:
  static_files:
